apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: result
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: result
    spec:
      containers:
      - image: wpatterson134/test_result:16
        name: vote-result
        resources: {}
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:post@db:5432/db
        - name: REDIS_URL
          value: redis:6379
status: {}
