apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vote
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vote
    spec:
      containers:
      - image: wpatterson134/test_vote:121
        name: vote
        resources: {}
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:post@db:5432/db
        - name: REDIS_URL
          value: redis:6379
status: {}
