apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: worker
    spec:
      containers:
      - image: schoolofdevops/worker:latest
        name: worker
        resources: {}
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:post@db:5432/db
        - name: REDIS_URL
          value: redis:6379
status: {}
